### ISSUE TITLE
Inconsistent ZIP list in spatial data

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/reference-data#1]
https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_admin.csv has 123 ZIPs listed, https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_city_region_vid.csv has 121 ZIPs, https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_hca.csv has 134 (though we know this is a more extensive list), https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_to_region.csv has 121 ZIPs.

Shouldn't the zip_admin, zip_city_region_vid, and zip_to_region files have a consistent number of ZIPs? The city and region files have some the admin does not, so there is less overlap than implied by a difference of 2 ZIPs.

**Comment by elikern-kc** [comment]
Thanks Alastair! Can we review this discrepancy at our next informatics sprint meeting?

Eli Kern MPH RN | Epidemiologist (he/him)
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: ***@***.***<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

COVID-19 resources:

  *   Public Health's website: www.kingcounty.gov/COVID<http://www.kingcounty.gov/COVID>
  *   Public Health's blog: www.publichealthinsider.com<http://www.publichealthinsider.com/>
  *   Dr. David Kern's COVID-19 Literature Reviews<https://tinyurl.com/sm3yc2q>

From: Alastair Matheson ***@***.***>
Sent: Wednesday, March 24, 2021 10:06 AM
To: PHSKC-APDE/reference-data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PHSKC-APDE/reference-data] Inconsistent ZIP list in spatial data (#1)

[EXTERNAL Email Notice! ] External communication is important to us. Be cautious of phishing attempts. Do not click or open suspicious links or attachments.

https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_admin.csv<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPHSKC-APDE%2Freference-data%2Fblob%2Fmaster%2Fspatial_data%2Fzip_admin.csv&data=04%7C01%7Celi.kern%40kingcounty.gov%7C4d013b817dbc4cf170d108d8eee709f7%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C637522023365452023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FyJj9MV0z%2F%2FqOLHKKrbPjLQ5NjFgFg%2BsVngc%2FPVcb5I%3D&reserved=0> has 123 ZIPs listed, https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_city_region_vid.csv<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPHSKC-APDE%2Freference-data%2Fblob%2Fmaster%2Fspatial_data%2Fzip_city_region_vid.csv&data=04%7C01%7Celi.kern%40kingcounty.gov%7C4d013b817dbc4cf170d108d8eee709f7%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C637522023365452023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BTs8cr17DsVOLEPXZ5dSWSOD%2F5X18l1l0%2FxEW9JYLbM%3D&reserved=0> has 121 ZIPs, https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_hca.csv<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPHSKC-APDE%2Freference-data%2Fblob%2Fmaster%2Fspatial_data%2Fzip_hca.csv&data=04%7C01%7Celi.kern%40kingcounty.gov%7C4d013b817dbc4cf170d108d8eee709f7%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C637522023365461973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=stnyRuRckb2Oaub3Fe2Cng4QPk8B4pK0IjjPiA2acL8%3D&reserved=0> has 134 (though we know this is a more extensive list), https://github.com/PHSKC-APDE/reference-data/blob/master/spatial_data/zip_to_region.csv<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPHSKC-APDE%2Freference-data%2Fblob%2Fmaster%2Fspatial_data%2Fzip_to_region.csv&data=04%7C01%7Celi.kern%40kingcounty.gov%7C4d013b817dbc4cf170d108d8eee709f7%7Cbae5059a76f049d7999672dfe95d69c7%7C0%7C0%7C637522023365461973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L7%2B56pkpoLp%2FoaERQqp6nhnFIbQw2gqxRh2UVMfLYLc%3D&reserved=0> has 121 ZIPs.

Shouldn't the zip_admin, zip_city_region_vid, and zip_to_region files have a consistent number of ZIPs? The city and region files have some the admin does not, so there is less overlap than implied by a difference of 2 ZIPs.

-

**Comment by alastairmatheson** [comment]
For sure, let's do that

**Comment by alastairmatheson** [comment]
Fixed in https://github.com/PHSKC-APDE/reference-data/commit/758f459907374469934b4a1d0131dc3630001810

**Comment by alastairmatheson** [comment]
Four files (zip_admin, zip_city_region_vid, zip_to_city_coundil_dist, and zip_to_region) were consolidated into one file (zip_city_region_scc). 

In addition, the zip_hca file, which is a list of ZIPs we provide to the Health Care Authority (and other external parties) as a list of ZIPs to define King County in adminstrative data, was updated.

Here is a more specific list of changes made during the consolidation.

**zip_city_region_scc**
- The basis for the list of ZIPs in King County was the zip_admin file
- The PO box ZIP 98171 (Seattle) was added
- Field names were changed to use the geo_ prefix

**zip_admin**
- Some city names were updated (e.g., Woodinville/2counties is just Woodinville, Seattle/N.County is now Seattle/Shoreline)
- Some city names were changed: 98146 (Seattle to Burien/Seattle/White Center), 98148 (Seattle to Burien/Normandy Park/SeaTac), 98166 (Seattle to Burien/Normandy Park), 98168 (Seattle to Burien/SeaTac/Tukwila/White Center), 98178 (Seattle to Seattle/Bryn Mawr-Skyway), 98188 (Seattle to Tukwila/SeaTac), 98198 (Seattle to Des Moines/SeaTac)

**zip_city_region_vid/zip_to_region (these files had the same ZIP to region lists and mappings)**
- Some fields were dropped (region_vid from zip_city_region_vid and office_building from zip_to_region)
- Some ZIPs that straddled King County and another county were dropped: 98054 (Auburn/Redondo), 98068 (Snoqualmie Pass), 98082 (Mill Creek)
- The same city name changes above were made (the mismatch between the city as Seattle and the region as South for those ZIPs is now corrected)

**zip_to_city_coundil_dist**
- No changes were made, all ZIP to Seattle City Council mappings were preserved (though there are additional ZIPs identified as being in Seattle that do not map to a SCC district)

**zip_hca**
- Field names were changed to use the geo_ prefix
- The multiple county flag (geo_multi_county) was changed from string ('yes' or blank) to binary (0/1)
- City names were updated or changed as noted above
